### ISSUE TITLE
Historian crashes if one of the sequences is 0-length

### ISSUE THREAD

**Issue by bredelings** [evoldoers/historian#10]
Hi Ian,

I hope all is well with you!

If I include zero-length sequences in the alignment, I get the following:
```
Abort: Zero forward likelihood even in the absence of guide alignment constraints - this is not good
Stack trace:
historian() [0x51302e]
historian() [0x4a7aaa]
historian() [0x4afa9b]
historian() [0x418079]
historian() [0x417dc4]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea) [0x7ffb37193d0a]
historian() [0x406b5a]
terminate called without an active exception
Aborted
```

I'm doing some polishing of genome-to-genome multiple-alignments ("pan-genome alignments") by realigning chunks, and historian does quite well on these, I think with `-careful`.  Sometimes these chunks do have zero-length sequences.

No pressure, just logging the issue.

-BenRI

**Comment by ihh** [comment]
hmmm, interesting... thanks for the report. any idea if it's crashing when trying to align a zero-length to a zero-length sequence, or a zero-length to a finite-length?

**Comment by bredelings** [comment]
I did look in the debugger, but not very seriously yet.

However, I tried this:
```
>1
ATGC
>2
----
```

and got the same crash, so presumably zero-length to finite-length.
