### ISSUE TITLE
Using a guide tree creates faulty reconstruction results 

### ISSUE THREAD

**Issue by jpalmer37** [evoldoers/historian#3]
I am trying to reconstruct the ancestors of a publicly-available HIV sequence data set called `target` using Historian by feeding it a guide MSA and a guide tree. However, when I provide my guide tree, Historian creates a problematic output. 

Here's an overview of what I've tried as input to Historian already 
(`target` is the data set causing problems):

1) Guide MSA and guide alignment on a completely unrelated data set (F1):
`historian r -guide F1_MSA.fasta -tree F1.tree -output fasta > F1_recon.txt`
...which works fine and provides normal output: [F1_recon.txt](https://github.com/evoldoers/historian/files/2947379/F1_recon.txt)

2) Raw sequence file OR guide MSA file with no guide tree 
`historian r target.fasta -output fasta > target_recon.fasta`
`historian r -guide target_MSA.fasta -output fasta > target_recon.fasta`
...which generates normal output too, like the reconstruction file shown below
![target_recon_guidemsa_notree](https://user-images.githubusercontent.com/32370730/54055388-ea2c3900-41ba-11e9-8197-bb1f9078fd06.png)

4) Guide MSA file with a guide tree 
`historian r -guide target_MSA.fasta -tree target.tree -output fasta > target_recon.fasta`
...which creates a problematic reconstruction file (first 4 sequences only): [target_recon.txt](https://github.com/evoldoers/historian/files/2947416/target_recon_guideMSA_tree_.txt)
...and aligns like this in Aliview:
![target_alignment_withtree](https://user-images.githubusercontent.com/32370730/54055983-b7834000-41bc-11e9-94f0-20dfdab0e36c.png)

Tree: [target_tree.txt](https://github.com/evoldoers/historian/files/2947423/target_tree.txt) 
MSA: [target_MSA.txt](https://github.com/evoldoers/historian/files/2947425/target_MSA.txt)

Any advice or help would be greatly appreciated.

**Comment by ihh** [comment]
Hi John, sorry for the slow reply.
The guide tree you're using looks like it has some very long branches, could that be the problem? On very long branches, the most likely explanation for the data is often (counterintuitively) that the whole sequence has been deleted and another one reinserted.
Where did you obtain this guide tree?

**Comment by jpalmer37** [comment]
Hi Dr. Holmes,
Thanks for the response. We followed up on this exact same thought earlier too. We figured out that the errors were caused by our tree being scaled in time, with branch lengths in units of days (output of BEAST software).  Reverting the time-scaled tree back to units of expected substitutions/site led to a proper result.

**Comment by ihh** [comment]
Glad to hear it! If you have any other issues I'll try to respond more quickly... :)
