### ISSUE TITLE
Ancestor reconstructions

### ISSUE THREAD

**Issue by bredelings** [evoldoers/historian#6]
I'm very impressed at what historian can do!  It seems like it can/should replace PRANK, at the very least.  I will make sure to include it in any future benchmarks.

For the ancestral sequence reconstructions, two thoughts:
* maybe you could use N/X instead of `*` for an unknown letter?  I think that `*` can mean "stop codon" in some cases, and I don't think many people in bioinformatics use `*`
* how hard would it be to sample actually letters instead of N/X?  In mcmc mode where you write a number of different alignments, that could be useful.

**Comment by ihh** [comment]
Thanks Ben, sorry for the slow reply.

You're probably right that "N/X" would be better than "*", I've added this as a separate issue (#7).

It should sample ancestral sequences already if you specify the "-ancseq" option, was that not working for you or was it just unclear from the usage text? (The help message is a bit cryptic on this point, it's kind of a buried feature.)

I really need to update it to use [differential automata](https://twitter.com/ianholmes/status/1278043312109187073?s=20), but this is an unfunded project for me at this point...

**Comment by ihh** [comment]
I've now created a separate test for the `-ancseq` option (#11) so I am closing this issue.

**Comment by ihh** [comment]
@bredelings FYI, the use of N/X for ancestral wildcard characters is now allowed as of 3a292a7. Historian still uses asterisks for wildcards internally, which means that you still can't use "\*" to denote a stop codon (changing that would have required a bit more refactoring than I had time for), but at least it issues a warning if you try to use "\*" as an alphabet character. I think that modeling stop codons as allowable substitution states is a sufficiently niche application that it's probably fine to ask those users to represent their stop codons with something other than an asterisk.
