### ISSUE TITLE
Historian refuses to run with simple command:

### ISSUE THREAD

**Issue by bredelings** [evoldoers/historian#8]
On current master, I get:

```
$ historian a.fasta
You can't fix both tree and alignment when doing MCMC - you must sample one of them!
```

**Comment by bredelings** [comment]
This works fine with tag v1.1.0, so I'll just use that for now.

**Comment by ihh** [comment]
Hi Ben, can you attach the file `a.fasta` that you were using? I.

**Comment by bredelings** [comment]
Here it is:

[a.fasta.gz](https://github.com/evoldoers/historian/files/5314990/a.fasta.gz)

**Comment by bredelings** [comment]
I compiled with GCC, not clang, in case that makes a difference.  I am getting this error when compiling on a cluster with gcc-9.

**Comment by bredelings** [comment]
However, when compiling on my desktop with clang++ I am not getting the error.  weird.

**Comment by ihh** [comment]
Yeah, I just saw the same behavior (no error with clang, that is; I haven't tried gcc yet)
I'll dig into it when I can!

**Comment by bredelings** [comment]
Thanks!
