### ISSUE TITLE
Linking needs `-lpthread` on newer systems

### ISSUE THREAD

**Issue by bredelings** [evoldoers/historian#9]
On my desktop, but not the remote cluster, I get this:
```
clang++ -std=c++11 -g -O3 -I/usr/include  -Isrc -c -o obj/jcrna.o src/jcrna.cpp
clang++ -lstdc++ -lm -lgsl -lgslcblas -lm  -lz -o bin/historian obj/historian.o obj/alignpath.o obj/ctok.o obj/dayhoff.o obj/diagenv.o obj/ECMrest.o obj/ECMunrest.o obj/fastseq.o obj/forward.o obj/gamma.o obj/gason.o obj/jc.o obj/jcrna.o obj/jones.o obj/jsonutil.o obj/knhx.o obj/lg.o obj/logger.o obj/logsumexp.o obj/memsize.o obj/model.o obj/nexus.o obj/optparser.o obj/pairhmm.o obj/presets.o obj/profile.o obj/quickalign.o obj/recon.o obj/refiner.o obj/sampler.o obj/seqgraph.o obj/simulator.o obj/span.o obj/stockholm.o obj/sumprod.o obj/tree.o obj/util.o obj/wag.o 
/usr/bin/ld: obj/logger.o: in function `std::recursive_timed_mutex::_M_clocklock(int, timespec const&)':
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/mutex:336: undefined reference to `pthread_mutex_clocklock'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by ihh** [comment]
huh, pretty sure that thread code is completely unused in historian. I'm just going to try deleting it and see if it still passes the tests :-)

**Comment by bredelings** [comment]
I was getting this on my own project which has no thread code, so my impression was that some dependency (boost?) changed to use threading.

**Comment by ihh** [comment]
I think it's just the error/progress logging, which uses a mutex to make it threadsafe (because I first developed it for a threaded project). It seems to compile and run fine without it. I've just pushed a couple updates that remove all thread-related code and headers, I think it should compile without `-lpthread` now.

**Comment by ihh** [comment]
Although maybe if it's one of the libraries (boost or GSL) then it will still need it.

**Comment by bredelings** [comment]
Yay!  That worked.
